import numpy as np
import time
import os
import math
import json

def generate_wcon(time_arr, x_arr, y_arr, d_arr, original_file_name, wcon_file_name):
    assert(x_arr.shape == y_arr.shape)
    assert(time_arr.size == x_arr.shape[1])

    num_steps = time_arr.size

    Nbar = x_arr.shape[0]
    NSEG = int(Nbar - 1)
    D = 80e-6

    R = np.array([
        D / 2.0 * abs(math.sin(math.acos(((i) - NSEG / 2.0) / (NSEG / 2.0 + 0.2))))
        for i in range(Nbar)
    ]).reshape(-1, 1)

    dx = np.cos(d_arr)*R
    dy = np.sin(d_arr)*R

    px = np.zeros((2*Nbar, x_arr.shape[1]))
    py = np.zeros((2*Nbar, x_arr.shape[1]))

    px[:Nbar, :] = x_arr - dx
    px[Nbar:, :] = np.flipud(x_arr + dx) # Make perimeter counter-clockwise

    py[:Nbar, :] = y_arr - dy
    py[Nbar:, :] = np.flipud(y_arr + dy) # Make perimeter counter-clockwise

    timestamp_str = time.strftime("%Y-%m-%dT%H:%M:%S+00:00", time.gmtime())
    info = "Loaded: %s points from %s, saving %i frames" % (num_steps, original_file_name, num_steps)
    time_arr_list = time_arr.tolist()
    x_arr_list = x_arr.T.tolist()
    y_arr_list = y_arr.T.tolist()
    px_arr_list = px.T.tolist()
    py_arr_list = py.T.tolist()
    ptail = Nbar

    wcon_dict = {
        "metadata": {
            "who": "CelegansNeuromechanicalGaitModulation",
            "timestamp": timestamp_str,
            "protocol": "Generated by CelegansNeuromechanicalGaitModulation!"
        },
        "units": {
            "t": "s",
            "x": "micrometers",
            "y": "micrometers"
        },
        "comment": "Saved from CelegansNeuromechanicalGaitModulation data.",
        "note": info,
        "data": [
            {
                "id": "wormTest",
                "t": time_arr_list,
                "x": x_arr_list,
                "y": y_arr_list,
                "px": px_arr_list,
                "py": py_arr_list,
                "ptail": ptail
            }
        ]
    }

    with open(wcon_file_name, 'w') as wcon_file:
        json.dump(wcon_dict, wcon_file, indent=4)

    print("Generated WCON file: %s"%wcon_file_name)

def validate(wcon_file):
    import json, jsonschema

    wcon_schema = "wcon_schema.json"

    if not os.path.isfile("wcon_schema.json"):
        print("Cannot validate file: %s!! WCON schema %s not found!!"%(wcon_file, wcon_schema))
        return

    # The WCON schema
    with open(wcon_schema, "r") as wcon_schema_file:
        schema = json.loads(wcon_schema_file.read())

    # Our example WCON file
    with open(wcon_file, 'r') as infile:
        serialized_data = infile.read()

    # Load the whole JSON file into a nested dict.
    w = json.loads(serialized_data)

    # Validate the raw file against the WCON schema
    jsonschema.validate(w, schema)

    print("File %s is valid WCON!!"%wcon_file)


if __name__ == "__main__":

    pos_file_name = "simdata.csv"
    data = np.genfromtxt(pos_file_name, delimiter=",").T
    ts = data[0]

    x_offset = 1
    y_offset = 2
    d_offset = 3

    x_slice = data[x_offset::3][:]
    y_slice = data[y_offset::3][:]
    d_slice = data[d_offset::3][:]

    wcon_file_name = "simdata.wcon"

    generate_wcon(ts, x_slice, y_slice, d_slice, pos_file_name, wcon_file_name)
    validate(wcon_file_name) 
